### ISSUE TITLE
MasterSelection seems to favor 8 line displays

### ISSUE THREAD

**Issue by ckrinke** [apiriadmin/APIRI#11]
I'm having a little trouble getting the screen size, A, B or D corresponding to 4, 8 or 16 rows. It looks like MasterSelection/FrontPanelManager really likes to return only 8, even though I am using a 16 line display that supports the "Esc[c" command.

**Comment by gallagjm** [comment]
In order to remain compatible with existing front panel displays, the Front Panel API uses a different method at startup to ascertain the panel dimensions. The function "check_screen_size()" in ViewportManager.c contains this code, which has been tested to work on 16-line display. There are some debugging statements which may be enabled by defining the "DEBUG" preprocessor symbol in the same file, which are printed to stdout.
The "ESC[c" sequence is still handled by the API if sent by an application, but this sequence is not sent to the front panel display.
